language: node_js
node_js:
  - "stable"
env:
  matrix:
  - REACT=16.4
  - REACT=16.5
  - REACT=16.6
  - REACT=16.8
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
on:
  branch: master